const nameList = [
  "Aarav Sharma",
  "Maya Kapoor",
  "Rohan Mehra",
  "Ishita Singh",
  "Aditya Verma",
  "Neha Malhotra",
  "Kunal Desai",
  "Priya Bansal",
  "Arjun Sethi",
  "Simran Gill",
  "Kabir Khanna",
  "Tanya Oberoi",
  "Rahul Chauhan",
  "Ananya Arora",
  "Vivaan Bedi",
  "Nisha Kaur",
  "Devansh Puri",
  "Sanya Ahuja",
  "Manav Gupta",
  "Pooja Bajaj",
  "Rehan Kapoor",
  "Aisha Dugal",
  "Yash Rajput",
  "Meera Kohli",
  "Ishaan Grover",
  "Riya Chawla",
  "Siddharth Nanda",
  "Avni Mehta",
  "Ayaan Saluja",
  "Vanya Rathore",
  "Karan Oberoi",
  "Radhika Sethi",
  "Aman Gill",
  "Dia Sharma",
  "Laksh Khurana",
  "Saanvi Batra",
  "Arnav Malik",
  "Ritika Talwar",
  "Vihaan Ahluwalia",
  "Tara Wadhwa",
  "Krish Thakur",
  "Anvi Soni",
  "Om Sharma",
  "Pari Chopra",
  "Yuvraj Anand",
  "Aarohi Kalra",
  "Daksh Kapoor",
  "Navya Singh",
  "Zayan Kaur",
  "Samaira Kohli",
  "Ivaan Ahuja",
  "Kiara Bhalla",
  "Reyansh Sandhu",
  "Mahira Bajaj",
  "Aryan Walia",
  "Anika Sehgal",
  "Kabir Maan",
  "Shanaya Talreja",
  "Neil Chawla",
  "Myra Arora",
];

const messages = [
  "Hey, what's up?",
  "Let’s catch up soon.",
  "Call me when free.",
  "I’ll text you later.",
  "Good morning, stay blessed.",
  "See you tomorrow.",
  "Missing those old days.",
  "Come online for a while.",
  "How’s everything going?",
  "You’ll love this place.",
  "Feeling super lazy today.",
  "Check your inbox now.",
  "Where have you been?",
  "That’s a great idea.",
  "Movie night this weekend?",
  "Let’s plan a trip.",
  "I miss our talks.",
  "It’s raining so much.",
  "Working on a project.",
  "We should meet soon.",
  "Don’t overthink it.",
  "Guess what happened today.",
  "Such a crazy day.",
  "Take care of yourself.",
  "Feeling grateful today.",
  "You’ll ace it!",
  "That sounds so cool.",
  "When’s your birthday?",
  "Loved your last post.",
  "I’ll be there soon.",
  "Let’s order some pizza.",
  "Need a coffee break.",
  "Stop overthinking everything.",
  "Is it still raining?",
  "Your playlist is fire.",
  "So proud of you.",
  "Let’s go for brunch.",
  "I can’t believe this.",
  "Thanks for being there.",
  "What’s your weekend plan?",
  "Long time, no see.",
  "Everything happens for good.",
  "You look amazing today.",
  "Such a beautiful evening.",
  "Need some good vibes.",
  "I’m so excited!",
  "Hope you’re doing well.",
  "Miss those conversations.",
  "Let’s start a new series.",
  "Haven’t slept all night.",
  "Feeling super productive today.",
  "Good luck with exams.",
  "Your idea is brilliant.",
  "Who’s your favorite artist?",
  "This is so peaceful.",
  "Let’s catch a movie.",
  "Don’t be so dramatic.",
  "Weather is perfect today.",
  "Wish you were here.",
  "You totally nailed it.",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
export function geenrateRandomMessage() {
  return messages[Math.floor(Math.random() * messages.length)];
}
